// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOj5ai1TEaH8pAF7XIxXFIuhr-EqM-AQ',
    appId: '1:210011493069:web:e1ac56c31923d8c8e80f84',
    messagingSenderId: '210011493069',
    projectId: 'mealplanner-64039',
    authDomain: 'mealplanner-64039.firebaseapp.com',
    storageBucket: 'mealplanner-64039.appspot.com',
    measurementId: 'G-E7B8YTFZ9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6gFrHpo11hyf1tjOy9XXAlKQ1lzrPgxQ',
    appId: '1:210011493069:android:4b0dcd7861a4ed30e80f84',
    messagingSenderId: '210011493069',
    projectId: 'mealplanner-64039',
    storageBucket: 'mealplanner-64039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Fy2RTTggGQRcsOoyQfNxXm10pLN3LAQ',
    appId: '1:210011493069:ios:74c78f294f8245ade80f84',
    messagingSenderId: '210011493069',
    projectId: 'mealplanner-64039',
    storageBucket: 'mealplanner-64039.appspot.com',
    iosBundleId: 'com.example.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Fy2RTTggGQRcsOoyQfNxXm10pLN3LAQ',
    appId: '1:210011493069:ios:e42a51494cf68e83e80f84',
    messagingSenderId: '210011493069',
    projectId: 'mealplanner-64039',
    storageBucket: 'mealplanner-64039.appspot.com',
    iosBundleId: 'com.example.mealPlanner.RunnerTests',
  );
}
